# -*- coding: utf-8 -*-
"""Bar_Graph_in_Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14gEFB8PUbw59PJCgMiqQMjnno7zln2Oc
"""

import matplotlib.pyplot as plt
x = [1,2,3,4]
y = [1,4,9,16]
c = ["r","y","b","g"]
plt.plot(x,y)
plt.bar(x,y,color = c)
plt.show()

x = ["pyhton","c","c++","java","c#"]
y = [95,70,90,80,85]
c= ["m","r","g","b","y"]
plt.xlabel("Language")
plt.ylabel("number")
plt.title("Programming Langauges")
plt.bar(x,y,color = c)
plt.show()

x = ["pyhton","c","c++","java","c#"]
y = [95,70,90,80,85]
c= ["m","r","g","b","y"]
plt.xlabel("Language")
plt.ylabel("number")
plt.title("Programming Langauges")
plt.bar(x,y,color = c,align = "edge",edgecolor = "black",linewidth = 3,linestyle = ":")
plt.show()

x = ["pyhton","c","c++","java","c#"]
y = [95,70,90,80,85]
z = [10,20,30,40,50]
plt.xlabel("Language")
plt.ylabel("number")
plt.title("Programming Langauges")
plt.bar(x,y,label = "haha",color = "red")
plt.bar(x,z,label = "hehe",color = "yellow")
plt.legend()
plt.show()

import numpy as np

x = ["pyhton","c","c++","java","c#"]
y = [95,70,90,80,85]
z = [10,20,30,40,50]

width = 0.3
p = np.arange(len(x))
p1 = [j + width for j in p]

plt.xlabel("Language")
plt.ylabel("number")
plt.title("Programming Langauges")

plt.bar(p,y,width,label = "haha",color = "red")
plt.bar(p1,z,width,label = "hehe",color = "yellow")

plt.xticks(p+width/2,x,rotation = 20)
plt.legend()
plt.show()

x = ["pyhton","c","c++","java","c#"]
y = [95,70,90,80,85]
z = [10,20,30,40,50]

plt.xlabel("Language")
plt.ylabel("number")
plt.title("Programming Langauges")

plt.barh(x,y,label = "haha",color = "red")
plt.barh(x,z,label = "hehe",color = "yellow")

plt.legend()
plt.show()

import numpy as np

x = ["pyhton","c","c++","java","c#"]
y = [95,70,90,80,85]
z = [10,20,30,40,50]

width = 0.3
p = np.arange(len(x))
p1 = [j + width for j in p]

plt.xlabel("Language")
plt.ylabel("number")
plt.title("Programming Langauges")

plt.barh(p,y,width,label = "haha",color = "red")
plt.barh(p1,z,width,label = "hehe",color = "yellow")

plt.xticks(p+width/2,x,rotation = 20)
plt.legend()
plt.show()

