# -*- coding: utf-8 -*-
"""Boxplot_matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBxwomPvIuZa8eB5x1V-VynGzO3HAYIs
"""

import matplotlib.pyplot as plt

x = [10,20,30,40,50,60,70]

plt.boxplot(x)
plt.show()

plt.boxplot(x,notch = True)
plt.show()

plt.boxplot(x,vert= False)
plt.show()

plt.boxplot(x,widths = 0.8)
plt.show()

plt.boxplot(x,labels = ["redcandle"],showmeans = True)
plt.legend()
plt.show()

x = [10,20,30,40,50,60,70,120]

plt.boxplot(x)
plt.show()

x = [10,20,30,40,50,60,70,120,130]

plt.boxplot(x)
plt.show()

x = [10,20,30,40,50,60,70,120]

plt.boxplot(x,labels = ["red candle"],whis = 2)
plt.show()

x = [10,20,30,40,50,60,70,120]

plt.boxplot(x,labels = ["red candle"],sym = 'g+')
plt.show()

x = [10,20,30,40,50,60,70]
X1 = [100,200,300,400,500,600,700]
X2 = [15,20,35,40,55,60,75,80,99]

y = [x,X1,X2]

plt.boxplot(y,labels = ["red candle","wick","green candle"],whis = 2)
plt.show()

