# -*- coding: utf-8 -*-
"""Histogram plot .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGmCPKnRpxeIJ8W2GAnEaduxEbjmmeNX
"""

import matplotlib.pyplot as plt
import numpy as np
import random

x = np.random.randint(10,60,(50))
print(x)

no = [14,35, 15, 21, 57, 19, 47, 29, 42, 52, 54, 55, 57, 44, 37, 28, 53, 10, 17, 48, 38, 23, 26, 21, 39,
 41, 22, 10, 36, 49, 48, 27, 41, 50, 23, 27, 35, 53, 32, 52, 25, 59, 41, 34, 28, 25, 39, 55, 23,
 16, 39]

plt.hist(no,color = "g",edgecolor = "black")
plt.title("Histogram")
plt.xlabel("Number")
plt.ylabel("Frequency")
plt.show()

no = [14,35, 15, 21, 57, 19, 47, 29, 42, 52, 54, 55, 57, 44, 37, 28, 53, 10, 17, 48, 38, 23, 26, 21, 39,
 41, 22, 10, 36, 49, 48, 27, 41, 50, 23, 27, 35, 53, 32, 52, 25, 59, 41, 34, 28, 25, 39, 55, 23,
 16, 39]
l = [10,20,30,40,50,60]
plt.hist(no,color = "g",bins = l,edgecolor = "black",cumulative = -1)
plt.title("Histogram")
plt.xlabel("Number")
plt.ylabel("Frequency")
plt.show()

no = [14,35, 15, 21, 57, 19, 47, 29, 42, 52, 54, 55, 57, 44, 37, 28, 53, 10, 17, 48, 38, 23, 26, 21, 39,
 41, 22, 10, 36, 49, 48, 27, 41, 50, 23, 27, 35, 53, 32, 52, 25, 59, 41, 34, 28, 25, 39, 55, 23,
 16, 39]
l = [10,20,30,40,50,60]
plt.hist(no,color = "g",bins = l,edgecolor = "black",histtype = 'step')
plt.title("Histogram")
plt.xlabel("Number")
plt.ylabel("Frequency")
plt.show()

no = [14,35, 15, 21, 57, 19, 47, 29, 42, 52, 54, 55, 57, 44, 37, 28, 53, 10, 17, 48, 38, 23, 26, 21, 39,
 41, 22, 10, 36, 49, 48, 27, 41, 50, 23, 27, 35, 53, 32, 52, 25, 59, 41, 34, 28, 25, 39, 55, 23,
 16, 39]
l = [10,20,30,40,50,60]
plt.hist(no,color = "g",bins = l,edgecolor = "black",orientation = 'horizontal',rwidth = 0.4)
plt.title("Histogram")
plt.xlabel("Number")
plt.ylabel("Frequency")
plt.show()

no = [14,35, 15, 21, 57, 19, 47, 29, 42, 52, 54, 55, 57, 44, 37, 28, 53, 10, 17, 48, 38, 23, 26, 21, 39,
 41, 22, 10, 36, 49, 48, 27, 41, 50, 23, 27, 35, 53, 32, 52, 25, 59, 41, 34, 28, 25, 39, 55, 23,
 16, 39]
l = [10,20,30,40,50,60]

plt.hist(no,color = "g",bins = l,edgecolor = "black",label = "data")
plt.title("Histogram")
plt.xlabel("Number")
plt.ylabel("Frequency")
plt.axvline(45,color = "r",label = "Mean")
plt.legend()
plt.show()

