# -*- coding: utf-8 -*-
"""pie_chart_matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmua8deRHgFD79jpxYEhRDAsPah5Afy-
"""

import matplotlib.pyplot as plt
x = [10,20,30,40]
y = ["c","c++","python","java"]
plt.pie(x,labels = y)
plt.show()

x = [10,20,30,40]
y = ["c","c++","python","java"]
ex = [0.1,0,0.3,0]
c = ["red","green","blue","yellow"]
plt.pie(x,labels = y,explode = ex,autopct = "%0.1f%%")
plt.show()

x = [10,20,30,40]
y = ["c","c++","python","java"]
ex = [0.1,0,0,0]
c = ["red","green","blue","yellow"]
plt.pie(x,labels = y,explode = ex,autopct = "%0.1f%%",shadow = True,radius = 1,labeldistance = 1.1,startangle = 360,counterclock = False,center=(3,6))
plt.title("Programming Data")
plt.legend()
plt.show()

x = [10,20,30,40]
x1 = [40,70,20,97]
y = ["c","c++","python","java"]
c = ["red","green","blue","yellow"]

plt.pie(x,labels = y,radius = 1)
plt.pie(x1,radius = 0.5,colors = c)
plt.legend()
plt.show()

x = [10,20,30,40]
x1 = [40,70,20,97]
y = ["c","c++","python","java"]
c = ["red","green","blue","yellow"]

plt.pie(x,labels = y,radius = 1)
plt.pie([1],colors="w",radius = 0.5)
plt.legend()
plt.show()

x = [10,20,30,40]
x1 = [40,70,20,97]
y = ["c","c++","python","java"]
c = ["red","green","blue","yellow"]

plt.pie(x,labels = y,radius = 1.5)
cr = plt.Circle(xy = (0,0),radius = 1,facecolor = "w")
plt.gca().add_artist(cr)

plt.show()

