# -*- coding: utf-8 -*-
"""Save-fig_&_change-of-axis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhBDWJYR2P51FCTeLmD5szMrO0b1_nBq
"""

import matplotlib.pyplot as plt
x = [1,2,3,4,5]
y = [1,4,9,16,25]
plt.plot(x,y)
plt.savefig('plo.pdf',dpi = 3000,facecolor = "g") # dpi = clarity
plt.show()

"""**CHANGE AXIS IN MATPLOTLIB**"""

X = [1,2,3,4,5]
Y = [3,1,5,9,4]
plt.plot(X,Y)
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.xticks(x, labels = ["python","c","c++","java","dsa"])
plt.yticks(y) #only shows the values which have been plotted
plt.show()

X = [1,2,3,4,5]
Y = [3,1,5,9,4]
plt.plot(X,Y)
plt.xlim(0,10)
plt.ylim(0,20)  #index increases
plt.show()

X = [1,2,3,4,5]
Y = [3,1,5,9,4]
plt.plot(X,Y)
plt.axis([0,10,0,7])
plt.show()

