# -*- coding: utf-8 -*-
"""Stem_plot_matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xKmtc6eyB16wbjn9M8Xdh89LgxWfwmr
"""

import matplotlib.pyplot as plt
x = [1,2,3,4,5,6]
y = [10,8,6,5,4,3]
plt.stem(x,y)
plt.show()

x = [1,2,3,4,5,6]
y = [10,8,6,5,4,3]
plt.stem(x,y,linefmt = ':')
plt.show()

x = [1,2,3,4,5,6]
y = [10,8,6,5,4,3]
plt.stem(x,y,linefmt = ':',markerfmt = "r+",bottom = 1.5,basefmt = "magenta")
plt.legend("python")
plt.show()

plt.stem(x,y,linefmt = ':',markerfmt = "r+",bottom = 1.5,basefmt = "magenta",orientation = "horizontal")
plt.legend("python")
plt.show()

