# -*- coding: utf-8 -*-
"""step-plot_&_Fill_in_between_plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tPyHbmsjubAmd4lKTH9-fZX9h6R8I0D

# STEP **PLOT**
"""

import matplotlib.pyplot as plt
x = [1,2,3,4,5]
y = [1,4,9,16,25]
plt.step(x,y)
plt.show()

x = [1,2,3,4,5]
y = [12,6,4,10,1]
plt.step(x,y,marker = "o",color = "r",label = "python")
plt.legend()

plt.title("python")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.grid()
plt.show()

"""# FILL BETWEEN **PLOT**"""

X = [1,2,3,4,5]
Y = [1,2,5,4,3]
plt.plot(X,Y,color = "r",label = "python")
plt.legend()
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.fill_between(X,Y,color = "y")
plt.show()