# -*- coding: utf-8 -*-
"""Sub_plot-in-Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5SEOV0hTMpIc8sW8tugG7XxfNXC04nv
"""

import matplotlib.pyplot as plt
x = [1,2,3,4]
y = [1,4,9,16]
plt.plot(x,y,color = "m")
plt.show()

x = [1,2,3,4]
y = [1,4,9,16]

plt.plot(x,y,color = "m")

plt.pie([1],colors = "r")

x1 = [10,20,30,40]
plt.pie(x)

x2 = ["a","s","w","i"]
y2 = [20,40,60,80]
plt.bar(x2,y2)
plt.show()

x = [1,2,3,4]
y = [1,4,9,16]
plt.subplot(2,2,1)
plt.plot(x,y,color = "m")

plt.subplot(2,2,2)
plt.pie([1],colors = "r")

x1 = [10,20,30,40]
plt.subplot(2,2,3)
plt.pie(x)

x2 = ["a","s","w","i"]
y2 = [20,40,60,80]
plt.subplot(2,2,4)
plt.bar(x2,y2)

plt.show()

