# -*- coding: utf-8 -*-
"""Text_in_matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gX2iWAcSVWGPz5cESvXQhVKlbzQ4FbPz
"""

import matplotlib.pyplot as plt
x= [2,5,7,9,3]
y = [2,9,5,3,0]

plt.plot(x,y)
plt.title("My first graph",fontsize = 15)
plt.xlabel("Days")
plt.ylabel("Python")

plt.text(2,5,"python",fontsize = 15,style = "italic",bbox = {"facecolor":"red"})

plt.annotate("java",xy = (3,2),xytext = (4,4),arrowprops = dict(facecolor = "black",shrink = 100))
plt.show()

